### ISSUE TITLE
[BUG] Trobert heroes quest error

### ISSUE THREAD

**Issue by titandino** [DarkanRS/world-server#268]
```
Error creating dialogue: TrobertHeroesQuestD - Cannot invoke "com.rs.game.content.dialogue.Dialogue.getHead()" because "this.current" is null
java.lang.RuntimeException: Error creating dialogue: TrobertHeroesQuestD - Cannot invoke "com.rs.game.content.dialogue.Dialogue.getHead()" because "this.current" is null
	at com.rs.game.content.dialogue.Conversation.getStart(Conversation.java:98)
	at com.rs.game.content.quests.handlers.heroesquest.BrimhavenHeroesQuest$6.handle(BrimhavenHeroesQuest.java:117)
	at com.rs.game.content.quests.handlers.heroesquest.BrimhavenHeroesQuest$6.handle(BrimhavenHeroesQuest.java:111)
	at com.rs.plugin.PluginMethodRepository.handle(PluginMethodRepository.java:42)
	at com.rs.plugin.PluginManager.handle(PluginManager.java:175)
	at com.rs.net.decoders.handlers.NPCHandler.lambda$handleOption1$0(NPCHandler.java:275)
	at com.rs.game.model.entity.interactions.StandardEntityInteraction.interact(StandardEntityInteraction.java:42)
	at com.rs.game.model.entity.interactions.EntityInteraction.process(EntityInteraction.java:66)
	at com.rs.game.model.entity.interactions.InteractionManager.process(InteractionManager.java:31)
	at com.rs.game.model.entity.Entity.processEntity(Entity.java:877)
	at com.rs.game.model.entity.player.Player.processEntity(Player.java:994)
	at com.rs.cores.WorldThread.run(WorldThread.java:72)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by JesseGuerrero** [comment]
You can close
